version: "3"
services:
  # Infrastructure
  #neo4j:
  #  image: neo4j:4.4.25-enterprise
  #  restart: always
  #  ports:
  #    - "7474:7474"
  #    - "7687:7687"
  #  volumes:
  #    - "./neo4j-net.jar:/plugins/neo4j-net.jar"
  #    - "/tmp/neo4j/data:/data"
  #    - "/tmp/neo4j/import:/var/lib/neo4j/import"
  #  environment:
  #    - NEO4J_AUTH=neo4j/12345
  #    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
  #    - NEO4J_dbms_allow__upgrade=true
  #    - NEO4J_dbms_logs_debug_level=DEBUG
  #    - NEO4J_apoc_export_file_enabled=true
  #    - NEO4J_apoc_import_file_enabled=true
  #    - NEO4J_apoc_import_file_use__neo4j__config=true
  #    - NEO4JLABS_PLUGINS=["apoc", "n10s"]
  #    - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*,n10s.*,net.*
  #    - NEO4J_dbms_security_procedures_allowlist=apoc.*,algo.*,n10s.*,net.*
  #    - NEO4J_dbms_unmanaged__extension__classes=n10s.endpoint=/rdf
  #  networks: 
  #    - smartrepo

  neo4j:
    image: neo4j:5.11
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - "./neo4j-net.jar:/plugins/neo4j-net.jar"
      - /tmp/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/12345-password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
        interval: 5s
        timeout: 3s
        retries: 5
    networks:
      - smartrepo
  # Shared services
  smartrepo:
    image: smartrepo
    links:
      - neo4j
    depends_on:
      - neo4j
    expose:
      - "7070"
    networks: 
      - smartrepo
networks:
  smartrepo:
    driver: bridge