version: "3"
services:
  # Infrastructure
  neo4j:
    image: neo4j:latest
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - "./neo4j-net.jar:/plugins/neo4j-net.jar"
      - /tmp/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/12345-password
      - NEO4J_PLUGINS=["apoc","apoc-extended"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*,net.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,algo.*,net.*
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
        interval: 5s
        timeout: 3s
        retries: 5
    networks:
      - smartrepo
  # Shared services
  smartrepo:
    image: smartrepo
    links:
      - neo4j
    depends_on:
      - neo4j
    expose:
      - "7070"
    networks: 
      - smartrepo
networks:
  smartrepo:
    driver: bridge