version: "3"
services:
  # Infrastructure
  neo4j:
    image: neo4j:4.2.1-enterprise
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "/neo4j/plugins:/plugins"
      - "/neo4j/data:/data"
      - "/neo4j/import:/var/lib/neo4j/import"
    environment:
      - NEO4J_AUTH=neo4j/12345
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc", "n10s"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*,n10s.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,algo.*,n10s.*
      - NEO4J_dbms_unmanaged__extension__classes=n10s.endpoint=/rdf
    networks: 
      - smartrepo
  # Shared services
  smartrepo:
    image: smartrepo
    links:
      - neo4j
    depends_on:
      - neo4j
    expose:
      - "7070"
    networks: 
      - smartrepo
networks:
  smartrepo:
    driver: bridge